name: cs5530-project
channels:
  - conda-forge
dependencies:
  - absl-py=1.4.0
  - appnope=0.1.3
  - asttokens=2.2.1
  - backcall=0.2.0
  - certifi=2022.12.7
  - click=8.1.3
  - cycler=0.11.0
  - decorator=5.1.1
  - fonttools=4.38.0
  - huggingface-hub=0.13.4
  - idna=3.4
  - ipykernel=6.21.2
  - ipython=8.10.0
  - jedi=0.18.2
  - jinja2=3.1.2
  - joblib=1.2.0
  - jupyter_client=8.0.3
  - jupyter_core=5.2.0
  - kiwisolver=1.4.4
  - mpmath=1.3.0
  - networkx=2.6.3
  - nltk=3.6.5
  - numpy=1.21.4
  - pandas=1.3.4
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - prompt-toolkit=3.0.22
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - pygments=2.10.0
  - pyparsing=3.0.6
  - python=3.9
  - python-dateutil=2.8.2
  - pytorch=1.9.1
  - pytz=2021.3
  - pyyaml=6.0
  - regex=2021.11.1
  - requests=2.26.0
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - six=1.16.0
  - tokenizers=0.10.3
  - torchaudio=0.9.1
  - torchvision=0.10.1
  - tqdm=4.62.3
  - transformers=4.11.3
  - urllib3=1.26.7
  - wcwidth=0.2.5
  - wordcloud=1.8.1
  - pip
  - pip:
    - charset-normalizer==2.0.6
    - comm==0.1.2
    - contourpy==1.0.7
    - executing==0.8.1
    - filelock==3.3.1
    - matplotlib==3.4.3
    - matplotlib-inline==0.1.2
    - nest-asyncio==1.5.4
    - pure-eval==0.2.3
    - rouge-score==0.0.4
    - stack-data==0.0.4
    - summarizer==0.0.7
    - sympy==1.8
    - threadpoolctl==3.1.0
    - typing_extensions==4.0.1
